### ISSUE TITLE
`test-coordinates_to_geometry.R` and `test-get_level_layer.R` error if sf adds attributes to sf objects

### ISSUE THREAD

**Issue by mikemahoney218** [josesamos/geodimension#3]
Hi there!

As currently written, `test-coordinates_to_geometry.R` and `test-get_level_layer.R` are partially testing that the underlying sf object never changes. Specifically, these three tests will throw errors if sf adds any attributes to sf objects:

https://github.com/josesamos/geodimension/blob/3d1109d0a6ea9493e07df7f9b964d98c02bf511e/tests/testthat/test-coordinates_to_geometry.R#L9-L57

https://github.com/josesamos/geodimension/blob/3d1109d0a6ea9493e07df7f9b964d98c02bf511e/tests/testthat/test-get_level_layer.R#L11-L25

https://github.com/josesamos/geodimension/blob/3d1109d0a6ea9493e07df7f9b964d98c02bf511e/tests/testthat/test-get_level_layer.R#L32-L90

The issue is that by testing if your objects contain _exactly_ those attributes, rather than if they contain the attributes you're concerned about, you're partially testing internal implementation details of the sf object that aren't guaranteed to remain the same over time. [There's a bit more about how testing the attributes of objects created by other packages can be a problem on the Tidyverse blog](https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/#testing-testing).

At the moment, [we're trying to add a new attribute to sf objects](https://github.com/r-spatial/sf/pull/2212), which [causes these three tests to error](https://github.com/r-spatial/sf/issues/2277). I'm writing to ask if you'd consider changing these tests to allow sf to improve the internal structure of sf objects.

Specifically, if I understand these tests correctly, I think you're testing to make sure that these objects are (a) being converted to sf objects and (b) contain the correct columns? Would you consider updating these tests to use `testthat::expect_s3_class(<object>, "sf")` and `testthat::expect_equal(sf::st_agr(<object>), structure(<target agr>))`? That would mean you're only testing "public" parts of the sf object and wouldn't block development on sf itself.

If you're open to it, I'd be happy to send you a PR to make these changes!

**Comment by josesamos** [comment]
Hi!

I want to review the entire package, but it will still take a few weeks to have a new version. I understand the problem and for now what I have done is eliminate those tests and I am going to send it to CRAN so that these problems do not arise with the changes in the sf package. I am sorry for any inconvenience caused.

**Comment by josesamos** [comment]
It is on its way to CRAN.

**Comment by mikemahoney218** [comment]
Thank you! Let me know if I can be any help replacing these tests.
